# Generated by Django 4.0 on 2021-12-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_unit_price_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventory',
            new_name='main_inventory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
