# Generated by Django 4.0 on 2021-12-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_inventory_product_main_inventory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
