# Generated by Django 4.0 on 2021-12-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
